### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by devunion** [bcarlin/flask-scss#14]
Hello, I've tried to use the extension with the last version of ZURB Foundation framework. But got the next error message:

  File "/usr/local/lib/python2.7/dist-packages/flaskext/scss.py", line 120, in update_scss
    self.compile_scss(asset, dest_path)
  File "/usr/local/lib/python2.7/dist-packages/flaskext/scss.py", line 129, in compile_scss
    fo.write(self.compiler(fi.read()))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xbb' in position 186557: ordinal not in range(128)

I've added the next changes in order to fix the problem:

        with open(dest_path, 'w') as fo:
            with open(asset) as fi:
>>                fo.write(self.compiler(fi.read()).encode('utf-8'))

Now it works for me without problems. I'm not 100% sure if this is the best way to fix the issue. Could you review it and update the plugin if necessary? 

Thank you!

**Comment by bcarlin** [comment]
Thank you ! 

It has been fixed in 6df882c217096d47b54adb137717b4f4264244d4
